### ISSUE TITLE
Create Linux implementation

### ISSUE THREAD

**Issue by erikmav** [microsoft/CopyOnWrite#10]
Linux version is TODOs and NotImplementedExceptions

**Comment by danmoseley** [comment]
If it's possible to do, we should do it in File.Copy itself. https://github.com/dotnet/runtime/pull/79243#issuecomment-1560324824

**Comment by erikmav** [comment]
Sure, see the Microsoft.Build.CopyOnWrite SDK which copies the Copy task code and adds in this library. Extend this library to all OSes and make use of it in Copy task in MSBuild.

**Comment by codingdave** [comment]
I was very happy to find this library and after reading the Readme I was sure it will work but then I run into this exception on Linux.

    Exception has occurred: CLR/System.NotImplementedException
    Exception thrown: 'System.NotImplementedException' in CopyOnWrite.dll: 'The method or operation is not implemented.'
   at Microsoft.CopyOnWrite.Linux.LinuxCopyOnWriteFilesystem.CopyOnWriteLinkSupportedInDirectoryTree(String rootDirectory, Boolean pathIsFullyResolved)

If the library does not have Linux support yet, it should be documented up-front.

@danmoseley adding the COW feature to File.Copy was even better as this was the first place I was checking for COW support.

**Comment by erikmav** [comment]
Added a note in README about the missing support.

**Comment by rainersigwald** [comment]
On Linux, you should just pass through to the BCL implementation of `File.Copy()`. It is copy-on-write enlightened since .NET 7: https://github.com/dotnet/runtime/pull/64264.

**Comment by codingdave** [comment]
That are awesome news and a reason to change .NET 6 to 7 on my Synology box. Thanks for the information!

**Comment by erikmav** [comment]
Closing issue as unneeded. README.md updated with info about possible Windows future plus Mac and Linux.
