### ISSUE TITLE
Create Mac implementation

### ISSUE THREAD

**Issue by erikmav** [microsoft/CopyOnWrite#11]
Mac version is TODOs and NotImplementedExceptions

**Comment by rainersigwald** [comment]
This is likely unnecessary; the current plan is for .NET to do it for all `File.Copy`: https://github.com/dotnet/runtime/pull/79243

**Comment by slang25** [comment]
Now that `File.Copy` support copy on write for macOS & Linux, would we expect this library to be used as the basis for Windows ReFS implementation of COW for `File.Copy`?

**Comment by erikmav** [comment]
Closing issue as unneeded. README.md updated with info about possible Windows future plus Mac and Linux.
