### ISSUE TITLE
Implementation on NTFS could be possible too by hardlinks.

### ISSUE THREAD

**Issue by pvones** [microsoft/CopyOnWrite#40]
This could be implemented on NTFS too using the hardlink feature. There is already a feature request for it: https://developercommunity.visualstudio.com/t/Use-file-system-hard-links-instead-of-co/1660923

**Comment by erikmav** [comment]
MSBuild already has settings to use hardlinks. See https://learn.microsoft.com/en-us/visualstudio/msbuild/copy-task?view=vs-2022 and look for 'hardlink'. The problem with hardlinks is that they are not safe for general use: If there are two links to the same underlying data blob on disk, and two different threads attempt to write at the same time, file lock errors can result, and the resulting contents of the links might not match expectations.
